@startuml
entity User {
    *userId: int
    name: string
    email: string
    password: string
    phoneNumber: string
}

entity Reservation {
    *reservationId: int
    status: string
    userId: int
    showId: int
    paymentId: int
}

entity Payment {
    *paymentId: int
    amount: float
    status: string
    reservationId: int
}

entity Movie {
    *movieId: int
    title: string
    genre: string
    duration: int
    director: string
    summary: string
    rating: float
}

entity Show {
    *showId: int
    date: Date
    time: Time
    movieId: int
    hallId: int
}

entity Hall {
    *hallId: int
    name: string
    capacity: int
}

entity Seat {
    *seatId: int
    number: string
    isAvailable: boolean
    hallId: int
}

' روابط
User ||--o{ Reservation : makes
Reservation ||--|| Payment : "has"
Reservation }o--|| Show : "for"
Show }o--|| Movie : "of"
Show }o--|| Hall : "in"
Hall ||--o{ Seat : contains
Reservation }o--o{ Seat : "books"
@enduml
